// Code generated by reset generator. DO NOT EDIT.

package model

// Reset сбрасывает состояние Url к начальным значениям.
func (x *Url) Reset() {
	if x == nil {
		return
	}
	x.Uuid = 0
	x.ShortUrl = ""
	x.OriginalUrl = ""
	x.UserID = ""
	x.IsDeleted = false
}

// Reset сбрасывает состояние UrlBatch к начальным значениям.
func (x *UrlBatch) Reset() {
	if x == nil {
		return
	}
	x.CorrelationId = ""
	if x.Url != nil {
		x.Url.Reset()
	}
}
