// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/al-tokarev/shortener/internal/repository/urlrepository (interfaces: RepositoryInterface)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	model "github.com/al-tokarev/shortener/internal/model"
	gomock "github.com/golang/mock/gomock"
)

// MockRepositoryInterface is a mock of RepositoryInterface interface.
type MockRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryInterfaceMockRecorder
}

// MockRepositoryInterfaceMockRecorder is the mock recorder for MockRepositoryInterface.
type MockRepositoryInterfaceMockRecorder struct {
	mock *MockRepositoryInterface
}

// NewMockRepositoryInterface creates a new mock instance.
func NewMockRepositoryInterface(ctrl *gomock.Controller) *MockRepositoryInterface {
	mock := &MockRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepositoryInterface) EXPECT() *MockRepositoryInterfaceMockRecorder {
	return m.recorder
}

// GetByOriginal mocks base method.
func (m *MockRepositoryInterface) GetByOriginal(arg0 string) (*model.Url, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByOriginal", arg0)
	ret0, _ := ret[0].(*model.Url)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByOriginal indicates an expected call of GetByOriginal.
func (mr *MockRepositoryInterfaceMockRecorder) GetByOriginal(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByOriginal", reflect.TypeOf((*MockRepositoryInterface)(nil).GetByOriginal), arg0)
}

// GetLastId mocks base method.
func (m *MockRepositoryInterface) GetLastId() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLastId")
	ret0, _ := ret[0].(int)
	return ret0
}

// GetLastId indicates an expected call of GetLastId.
func (mr *MockRepositoryInterfaceMockRecorder) GetLastId() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLastId", reflect.TypeOf((*MockRepositoryInterface)(nil).GetLastId))
}

// GetOriginalByShort mocks base method.
func (m *MockRepositoryInterface) GetOriginalByShort(arg0 string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOriginalByShort", arg0)
	ret0, _ := ret[0].(string)
	return ret0
}

// GetOriginalByShort indicates an expected call of GetOriginalByShort.
func (mr *MockRepositoryInterfaceMockRecorder) GetOriginalByShort(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOriginalByShort", reflect.TypeOf((*MockRepositoryInterface)(nil).GetOriginalByShort), arg0)
}

// InitializeStorage mocks base method.
func (m *MockRepositoryInterface) InitializeStorage() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InitializeStorage")
	ret0, _ := ret[0].(error)
	return ret0
}

// InitializeStorage indicates an expected call of InitializeStorage.
func (mr *MockRepositoryInterfaceMockRecorder) InitializeStorage() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InitializeStorage", reflect.TypeOf((*MockRepositoryInterface)(nil).InitializeStorage))
}

// Ping mocks base method.
func (m *MockRepositoryInterface) Ping() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping")
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockRepositoryInterfaceMockRecorder) Ping() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockRepositoryInterface)(nil).Ping))
}

// Save mocks base method.
func (m *MockRepositoryInterface) Save(arg0 *model.Url) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockRepositoryInterfaceMockRecorder) Save(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockRepositoryInterface)(nil).Save), arg0)
}

// SaveBatch mocks base method.
func (m *MockRepositoryInterface) SaveBatch(arg0 *[]model.Url) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveBatch", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveBatch indicates an expected call of SaveBatch.
func (mr *MockRepositoryInterfaceMockRecorder) SaveBatch(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveBatch", reflect.TypeOf((*MockRepositoryInterface)(nil).SaveBatch), arg0)
}
