// Code generated by reset generator. DO NOT EDIT.

package model

// Reset сбрасывает состояние URL к начальным значениям.
func (x *URL) Reset() {
	if x == nil {
		return
	}
	x.UUID = 0
	x.ShortURL = ""
	x.OriginalURL = ""
	x.UserID = ""
	x.IsDeleted = false
}

// Reset сбрасывает состояние Example к начальным значениям.
func (x *Example) Reset() {
	if x == nil {
		return
	}
	x.x = 0
	x.y = 0
	x.g = false
	clear(x.mapa)
}

// Reset сбрасывает состояние URLBatch к начальным значениям.
func (x *URLBatch) Reset() {
	if x == nil {
		return
	}
	x.CorrelationID = ""
	if x.URL != nil {
		x.URL.Reset()
	}
}
