package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"strings"
	"text/template"
)

const resetTemplate = `// Code generated by reset generator. DO NOT EDIT.

package {{.PackageName}}

{{range .Structs}}
// Reset сбрасывает состояние {{.Name}} к начальным значениям.
func (x *{{.Name}}) Reset() {
	if x == nil {
		return
	}
{{range .Fields}}	{{.ResetCode}}
{{end}}}
{{end}}`

type StructInfo struct {
	Name   string
	Fields []FieldInfo
}

type FieldInfo struct {
	ResetCode string
}

type PackageData struct {
	PackageName string
	Structs     []StructInfo
}

func main() {
	packages := make(map[string]*PackageData)

	filepath.Walk(".", func(path string, info os.FileInfo, err error) error {
		if err != nil || info.IsDir() {
			return nil
		}
		if !strings.HasSuffix(path, ".go") {
			return nil
		}
		if strings.HasSuffix(path, "_reset.gen.go") || strings.HasSuffix(path, "reset.gen.go") {
			return nil
		}

		collectStructs(path, packages)
		return nil
	})

	for dirPath, pkgData := range packages {
		if err := generateForPackage(dirPath, pkgData); err != nil {
			fmt.Fprintf(os.Stderr, "Error generating %s: %v\n", dirPath, err)
			os.Exit(1)
		}
	}
}

func collectStructs(filePath string, packages map[string]*PackageData) {
	fset := token.NewFileSet()
	file, err := parser.ParseFile(fset, filePath, nil, parser.ParseComments)
	if err != nil {
		return
	}

	dirPath := filepath.Dir(filePath)
	pkgData, exists := packages[dirPath]
	if !exists {
		pkgData = &PackageData{
			PackageName: file.Name.Name,
		}
		packages[dirPath] = pkgData
	}

	for _, decl := range file.Decls {
		genDecl, ok := decl.(*ast.GenDecl)
		if !ok || genDecl.Doc == nil {
			continue
		}

		if !hasResetComment(genDecl.Doc) {
			continue
		}

		for _, spec := range genDecl.Specs {
			typeSpec, ok := spec.(*ast.TypeSpec)
			if !ok {
				continue
			}

			structType, ok := typeSpec.Type.(*ast.StructType)
			if !ok {
				continue
			}

			structInfo := StructInfo{
				Name:   typeSpec.Name.Name,
				Fields: buildFields(structType),
			}

			pkgData.Structs = append(pkgData.Structs, structInfo)
		}
	}
}

func generateForPackage(dirPath string, pkgData *PackageData) error {
	if len(pkgData.Structs) == 0 {
		return nil
	}

	tmpl, err := template.New("reset").Parse(resetTemplate)
	if err != nil {
		return fmt.Errorf("parse template: %w", err)
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, pkgData); err != nil {
		return fmt.Errorf("execute template: %w", err)
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return fmt.Errorf("format source: %w", err)
	}

	outFile := filepath.Join(dirPath, "reset.gen.go")
	if err := os.WriteFile(outFile, formatted, 0644); err != nil {
		return fmt.Errorf("write file %s: %w", outFile, err)
	}

	fmt.Printf("Generated: %s\n", outFile)
	return nil
}

func buildFields(structType *ast.StructType) []FieldInfo {
	var fields []FieldInfo

	for _, field := range structType.Fields.List {
		fieldType := getType(field.Type)

		for _, name := range field.Names {
			fieldName := name.Name
			resetCode := generateResetCode(fieldName, fieldType)

			fields = append(fields, FieldInfo{
				ResetCode: resetCode,
			})
		}
	}

	return fields
}

func generateResetCode(fieldName, fieldType string) string {
	switch {
	case strings.HasPrefix(fieldType, "[]"):
		return fmt.Sprintf("x.%s = x.%s[:0]", fieldName, fieldName)
	case strings.HasPrefix(fieldType, "map["):
		return fmt.Sprintf("clear(x.%s)", fieldName)
	case strings.HasPrefix(fieldType, "*"):
		baseType := strings.TrimPrefix(fieldType, "*")
		if isPrimitive(baseType) {
			return fmt.Sprintf("if x.%s != nil { *x.%s = %s }", fieldName, fieldName, zeroValue(baseType))
		}
		return fmt.Sprintf("if x.%s != nil { x.%s.Reset() }", fieldName, fieldName)
	case fieldType == "string":
		return fmt.Sprintf("x.%s = \"\"", fieldName)
	case fieldType == "bool":
		return fmt.Sprintf("x.%s = false", fieldName)
	case isPrimitive(fieldType):
		return fmt.Sprintf("x.%s = 0", fieldName)
	default:
		return fmt.Sprintf("x.%s.Reset()", fieldName)
	}
}

func hasResetComment(doc *ast.CommentGroup) bool {
	for _, c := range doc.List {
		if strings.Contains(c.Text, "generate:reset") {
			return true
		}
	}
	return false
}

func getType(expr ast.Expr) string {
	switch t := expr.(type) {
	case *ast.Ident:
		return t.Name
	case *ast.StarExpr:
		return "*" + getType(t.X)
	case *ast.ArrayType:
		return "[]" + getType(t.Elt)
	case *ast.MapType:
		return "map[" + getType(t.Key) + "]" + getType(t.Value)
	case *ast.SelectorExpr:
		return getType(t.X) + "." + t.Sel.Name
	}
	return ""
}

func isPrimitive(t string) bool {
	switch t {
	case "int", "int8", "int16", "int32", "int64",
		"uint", "uint8", "uint16", "uint32", "uint64",
		"float32", "float64", "string", "bool", "byte", "rune":
		return true
	}
	return false
}

func zeroValue(t string) string {
	switch t {
	case "string":
		return ""
	case "bool":
		return "false"
	default:
		return "0"
	}
}
