package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"strings"
)

func main() {
	filepath.Walk(".", func(path string, info os.FileInfo, err error) error {
		if err != nil || info.IsDir() {
			return nil
		}
		if !strings.HasSuffix(path, ".go") {
			return nil
		}
		if strings.HasSuffix(path, "_reset.gen.go") {
			return nil
		}
		generateReset(path)
		return nil
	})
}

func generateReset(filePath string) {
	fset := token.NewFileSet()
	file, err := parser.ParseFile(fset, filePath, nil, parser.ParseComments)
	if err != nil {
		return
	}

	var buf bytes.Buffer
	found := false

	for _, decl := range file.Decls {
		genDecl, ok := decl.(*ast.GenDecl)
		if !ok {
			continue
		}

		if genDecl.Doc == nil {
			continue
		}

		hasReset := false
		for _, c := range genDecl.Doc.List {
			if strings.Contains(c.Text, "generate:reset") {
				hasReset = true
				break
			}
		}

		if !hasReset {
			continue
		}

		for _, spec := range genDecl.Specs {
			typeSpec, ok := spec.(*ast.TypeSpec)
			if !ok {
				continue
			}

			structType, ok := typeSpec.Type.(*ast.StructType)
			if !ok {
				continue
			}

			if !found {
				buf.WriteString(fmt.Sprintf("// Code generated by reset generator. DO NOT EDIT.\n\npackage %s\n\n", file.Name.Name))
				found = true
			}

			name := typeSpec.Name.Name
			buf.WriteString(fmt.Sprintf("// Reset сбрасывает состояние %s к начальным значениям.\n", name))
			buf.WriteString(fmt.Sprintf("func (x *%s) Reset() {\n", name))
			buf.WriteString("\tif x == nil { return }\n")

			for _, field := range structType.Fields.List {
				if len(field.Names) == 0 {
					continue
				}

				fieldName := field.Names[0].Name
				fieldType := getType(field.Type)

				switch {
				case strings.HasPrefix(fieldType, "[]"):
					buf.WriteString(fmt.Sprintf("\tx.%s = x.%s[:0]\n", fieldName, fieldName))
				case strings.HasPrefix(fieldType, "map["):
					buf.WriteString(fmt.Sprintf("\tclear(x.%s)\n", fieldName))
				case strings.HasPrefix(fieldType, "*"):
					baseType := strings.TrimPrefix(fieldType, "*")
					if isPrimitive(baseType) {
						buf.WriteString(fmt.Sprintf("\tif x.%s != nil { *x.%s = %s }\n", fieldName, fieldName, zeroValue(baseType)))
					} else {
						buf.WriteString(fmt.Sprintf("\tif x.%s != nil { x.%s.Reset() }\n", fieldName, fieldName))
					}
				case fieldType == "string":
					buf.WriteString(fmt.Sprintf("\tx.%s = \"\"\n", fieldName))
				case fieldType == "bool":
					buf.WriteString(fmt.Sprintf("\tx.%s = false\n", fieldName))
				case isPrimitive(fieldType):
					buf.WriteString(fmt.Sprintf("\tx.%s = 0\n", fieldName))
				default:
					buf.WriteString(fmt.Sprintf("\tx.%s.Reset()\n", fieldName))
				}
			}

			buf.WriteString("}\n\n")
		}
	}

	if !found {
		return
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		fmt.Printf("Format error: %v\n", err)
		return
	}

	outFile := strings.TrimSuffix(filePath, ".go") + "_reset.gen.go"
	os.WriteFile(outFile, formatted, 0644)
	fmt.Printf("Generated: %s\n", outFile)
}

func getType(expr ast.Expr) string {
	switch t := expr.(type) {
	case *ast.Ident:
		return t.Name
	case *ast.StarExpr:
		return "*" + getType(t.X)
	case *ast.ArrayType:
		return "[]" + getType(t.Elt)
	case *ast.MapType:
		return "map[" + getType(t.Key) + "]" + getType(t.Value)
	case *ast.SelectorExpr:
		return getType(t.X) + "." + t.Sel.Name
	}
	return ""
}

func isPrimitive(t string) bool {
	switch t {
	case "int", "int8", "int16", "int32", "int64",
		"uint", "uint8", "uint16", "uint32", "uint64",
		"float32", "float64", "string", "bool", "byte", "rune":
		return true
	}
	return false
}

func zeroValue(t string) string {
	switch t {
	case "string":
		return `""`
	case "bool":
		return "false"
	default:
		return "0"
	}
}
